[DEFAULT]
# Common title of the graphs
CommonTitle = 1 Mpps to 6 Mpps with 100 Kpps inc in 10s; No EWMA; 3s Rule wait; Loss ratio 0.01; Zoomed 10%%

# Appendix added to the output file name of the graphs
FileNameAppendix = zoomed

# Experiment run time
ExperimentTime = 260

# Rule install times comma separated
RuleInstallTimes =

# Start of X axis for the plots
XAxisStart = 45

# End of X axis for the plots
XAxisEnd = 50

# X axis step size for the plots
XAxisStep = 0.2

[TPUT]
# Plot resolution in microseconds
PlotResolution = 1000000

# DPU Maximum throughput
MaxDPUTput = 2.7

[RTT]
# Plot resolution in microseconds
PlotResolution = 10000

[LOSS]
# Plot resolution in microseconds
PlotResolution = 10000
