[DEFAULT]
# Common title of the graphs
CommonTitle = DPU Limit Set Workload

# Appendix added to the output file name of the graphs
FileNameAppendix =

# Experiment run time
ExperimentTime = 60

# Rule install times comma separated
RuleInstallTimes = 25.28,28.31,32.32,35.28,44.31,51.41,58.31

# Start of X axis for the plots
XAxisStart = 0

# End of X axis for the plots
XAxisEnd = 70

# X axis step size for the plots
XAxisStep = 5

[TPUT]
# Plot resolution in microseconds
PlotResolution = 1000000

# DPU Maximum throughput
MaxDPUTput = 2.6

[RTT]
# Plot resolution in microseconds
PlotResolution = 10000

[LOSS]
# Plot resolution in microseconds
PlotResolution = 10000
