[DEFAULT]
# Common title of the graphs
CommonTitle = 100 Kpps to 3 Mpps with 100 Kpps inc in 10s; EWMA a = 1; 3s Rule wait; Loss ratio 0.01

# Appendix added to the output file name of the graphs
FileNameAppendix =

# Experiment run time
ExperimentTime = 320

# Rule install times comma separated
RuleInstallTimes = 100.04,104.47,126.65,130.19,170.56,202.13,248.24,285.42

# Start of X axis for the plots
XAxisStart = 0

# End of X axis for the plots
XAxisEnd = 320

# X axis step size for the plots
XAxisStep = 10

[TPUT]
# Plot resolution in microseconds
PlotResolution = 1000000

# DPU Maximum throughput
MaxDPUTput = 1.2

[RTT]
# Plot resolution in microseconds
PlotResolution = 10000

[LOSS]
# Plot resolution in microseconds
PlotResolution = 10000
