[DEFAULT]
# Common title of the graphs
CommonTitle = TEST GRAPH

# Appendix added to the output file name of the graphs
FileNameAppendix =

# Experiment run time
ExperimentTime = 10

# Rule install times comma separated
RuleInstallTimes = 2,4,6,8

# Start of X axis for the plots
XAxisStart = 0

# End of X axis for the plots
XAxisEnd = 20

# X axis step size for the plots
XAxisStep = 2

[TPUT]
# Plot resolution in microseconds
PlotResolution = 1000000

# DPU Maximum throughput
MaxDPUTput = 3

[RTT]
# Plot resolution in microseconds
PlotResolution = 10000

[LOSS]
# Plot resolution in microseconds
PlotResolution = 10000
