[DEFAULT]
# Common title of the graphs
CommonTitle = 1 Mpps to 6 Mpps with 100 Kpps inc in 10s; EWMA a = 0.75; 3s Rule wait; Loss ratio 0.01

# Appendix added to the output file name of the graphs
FileNameAppendix =

# Experiment run time
ExperimentTime = 260

# Rule install times comma separated
RuleInstallTimes = 72.30,77.42,99.55,122.22,133.23,152.46,160.82,193.63

# Start of X axis for the plots
XAxisStart = 0

# End of X axis for the plots
XAxisEnd = 260

# X axis step size for the plots
XAxisStep = 10

[TPUT]
# Plot resolution in microseconds
PlotResolution = 1000000

# DPU Maximum throughput
MaxDPUTput = 2.7

[RTT]
# Plot resolution in microseconds
PlotResolution = 10000

[LOSS]
# Plot resolution in microseconds
PlotResolution = 10000
