[DEFAULT]
# Common title of the graphs
CommonTitle = 

# Appendix added to the output file name of the graphs
FileNameAppendix =

# Experiment run time
ExperimentTime = 30

# Rule install times comma separated
RuleInstallTimes = 

# Start of X axis for the plots
XAxisStart = 0

# End of X axis for the plots
XAxisEnd = 35

# X axis step size for the plots
XAxisStep = 5

[TPUT]
# Plot resolution in microseconds
PlotResolution = 1000000

# DPU Maximum throughput
MaxDPUTput = 0

[RTT]
# Plot resolution in microseconds
PlotResolution = 1000000

[LOSS]
# Plot resolution in microseconds
PlotResolution = 10000
