// Copyright (c) 2017, The Regents of the University of California.
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
// * Redistributions of source code must retain the above copyright notice, this
// list of conditions and the following disclaimer.
//
// * Redistributions in binary form must reproduce the above copyright notice,
// this list of conditions and the following disclaimer in the documentation
// and/or other materials provided with the distribution.
//
// * Neither the names of the copyright holders nor the names of their
// contributors may be used to endorse or promote products derived from this
// software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
// ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
// LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
// CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
// SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
// CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
// ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
// POSSIBILITY OF SUCH DAMAGE.

syntax = "proto3";

package dma.dmatrans.pb;

/**
 * Parameters for creating memory regions.
 *
 * `structure` is for specifying the data structure
 * to setup the shared memory with. If empty
 * or `plain` then no ds is assumed.
 * 
 * Current available options:
 * `plain`: No data structure
 * 'llist': Linked list
 * 
 * `memtyp` is for specifying method for accesing
 * memory:
 *  0 - Local memory access
 *  1 - DMA
 *  2 - RDMA
 *
 * `pcie` is for specifying the PCIe device to use for DMA.
 * This address might be different on the host and DPU
 */

message DMAArg {
  uint32 id = 1;          // ID of the region
  uint64 size = 2;        // Size of the region
  uint32 memtype = 3;     // Type of memory copy
  string structure = 4;   // Data structure to setup shared memory with
  string pci_addr = 5;   // PCIe device address to use for DMA
  bool init = 6;         // Initialize the memory
  uint64 num_keys = 7;   // KV pairs to pre-fill (0 = compiled-in default)
}

message DMAStatsResopnse {
  uint64 num_bytes = 1;   // Num bytes moved through doca DMA
}
